import Nav from '../../components/nav';
import '../styles/globals.css'
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Alistamiento de buques mercantes',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <title>{metadata.title}</title>
      </head>
      <body className={inter.className}>
        <Nav />
        {children}
        </body>
    </html>
  )
}
